[package]
name = "movies-docs-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.9.2"
log = "0.4.17"
env_logger ="0.10.0"
polars = "0.25.1"